module.exports = {
  data: [
    {
      Name: "Artboard1",
      Visibility: "Public",
      PageName: "signUpLogin_1",
      Head1: "primary",
      Head2: "",
      Search: "",
      Foot1: "primary-light",
      Foot2: "primary",
      Foot3: "secondary-dark",
      "Izquierda-Top": "60%",
      "Medio-Top": "",
      "Derecha-Top": "30%",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard2",
      Visibility: "Public",
      PageName: "viewArt_2",
      Head1: "primary",
      Head2: "secondary-dark",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "100%",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard3",
      Visibility: "Public",
      PageName: "alerts_onHover_3",
      Head1: "primary",
      Head2: "secondary-dark",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "100%",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard4",
      Visibility: "ArtistDashboard",
      PageName: "viewSpecificPiece_4",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "60%",
      "Medio-Top": "",
      "Derecha-Top": "30%",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "100%",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard5",
      Visibility: "ArtistDashboard",
      PageName: "viewSpecificPieceLg_5",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "60%",
      "Medio-Top": "",
      "Derecha-Top": "30%",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "100%",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard6",
      Visibility: "ArtistDashboard",
      PageName: "viewSpecificPiece2_6",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "100%",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "30%",
      "Derecha-Mid": "60%",
      "Izquierda-Bott": "100%",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard7",
      Visibility: "ArtistDashboard",
      PageName: "viewSpecificPiece3_6",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "100%",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "30%",
      "Derecha-Mid": "60%",
      "Izquierda-Bott": "100%",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard8",
      Visibility: "ArtistWorkDashboard",
      PageName: "workPiece_8",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "20%",
      "Medio-Top": "50%",
      "Derecha-Top": "30%",
      "Izquierda-Mid": "20%",
      "Derecha-Mid": "80%",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard9",
      Visibility: "ArtistProfileDashboard",
      PageName: "artistProfile_9",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "20%",
      "Medio-Top": "80%",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard10",
      Visibility: "Public",
      PageName: "artistProfilePosts_10",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "80%",
      "Medio-Top": "20%",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard11",
      Visibility: "Public",
      PageName: "artistProfileReviews_11",
      Head1: "primary",
      Head2: "primary-light",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "80%",
      "Medio-Top": "20%",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard12",
      Visibility: "CollectorDashboard",
      PageName: "collectorDashboard_12",
      Head1: "primary",
      Head2: "blue",
      Search: "Yes",
      Foot1: "",
      Foot2: "",
      Foot3: "secondary-dark",
      "Izquierda-Top": "20%",
      "Medio-Top": "50%",
      "Derecha-Top": "30%",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard13",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard14",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard15",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard16",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard17",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard18",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard19",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard20",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard21",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard22",
      Visibility: "",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
    {
      Name: "Artboard23",
      Visibility: "ArtistProfile",
      PageName: "",
      Head1: "",
      Head2: "",
      Search: "",
      Foot1: "",
      Foot2: "",
      Foot3: "",
      "Izquierda-Top": "",
      "Medio-Top": "",
      "Derecha-Top": "",
      "Izquierda-Mid": "",
      "Derecha-Mid": "",
      "Izquierda-Bott": "",
      "Derecha-Bott": "",
    },
  ],
};
